apiVersion: v2
name: knative-serving
description: A Helm chart for deploying knative-serving

type: application

version: 0.5.0

appVersion: "1.4.0"

dependencies:
  - name: knative-operator
    version: 0.5.x
    repository: https://cruxinformatics.github.io/triggermesh-charts
    condition: knative-operator.enabled
