name: Release Charts

concurrency: release-helm

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: 'dest'
          ref: 'gh-pages'
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Package Helm charts
        shell: bash
        run: |
          helm package charts/istio-operator -u -d dest
          helm package charts/keycloak -u -d dest
          helm package charts/knative-operator -u -d dest
          helm package charts/knative-targets -u -d dest
          helm package charts/koby -u -d dest
          helm package charts/tekton-operator -u -d dest
          helm package charts/triggerflow -u -d dest
          helm package charts/triggermesh-core -u -d dest


      - name: Push New Files
        shell: bash
        working-directory: dest
        run: |
          helm repo index . --url https://raw.githubusercontent.com/cruxinformatics/triggermesh-charts/gh-pages/
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add $(git ls-files -o --exclude-standard)
          git add index.yaml
          git commit -m "Updated from ref: $GITHUB_SHA"
          git push
